import { defineConfig } from 'vite';
import tailwindcss from '@tailwindcss/vite';

// Tailwind v4 is wired as a Vite plugin — no tailwind.config.js, no PostCSS.
// The single token source is src/theme.generated.css (@theme), generated by ../../scripts/build-tokens.js.
export default defineConfig({
  plugins: [tailwindcss()],
});
