import { cva, type VariantProps } from 'class-variance-authority';
import { forwardRef, type ButtonHTMLAttributes } from 'react';

// buttonVariants — a cva recipe built ENTIRELY from semantic Tailwind tokens generated by the @theme in
// index.css (bg-primary / text-card / bg-accent / text-on-accent / ring-accent / rounded-md ...). No raw
// hex/rgb, no --brand-* primitive refs, no off-grid arbitrary brackets — so it passes brand-lint as-is.
// Interaction states are pure CSS pseudo-variants, so a single rendered button exercises ALL of them:
//   default = base · hover: = :hover · focus-visible: = keyboard focus ring · active: = :active(pressed)
//   disabled: = :disabled · loading = the `loading` prop (drives aria-busy + the spinner + disabled).
export const buttonVariants = cva(
  // base: layout, focus ring (outline kept, never removed — a11y), disabled affordance, motion.
  'inline-flex items-center justify-center gap-2 rounded-md font-body font-semibold ' +
    'whitespace-nowrap select-none cursor-pointer transition-colors ' +
    'outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-surface ' +
    'disabled:opacity-50 disabled:cursor-not-allowed disabled:pointer-events-none',
  {
    variants: {
      variant: {
        primary: 'bg-primary text-card hover:bg-primary-900 active:bg-primary-900',
        accent: 'bg-accent text-on-accent hover:bg-accent-700 active:bg-accent-700',
        ghost:
          'bg-card text-ink border border-line hover:bg-primary-50 active:bg-primary-100',
      },
      size: {
        md: 'px-6 py-3', // 24px / 12px — on the 4px grid
        sm: 'px-4 py-2', // 16px / 8px
      },
    },
    defaultVariants: { variant: 'primary', size: 'md' },
  },
);

export interface ButtonProps
  extends ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  loading?: boolean;
}

// A token-true type ramp via inline vars (--text-16/--leading-16 live in the @theme) keeps the label on the
// shared type scale without arbitrary text-[..] brackets.
const LABEL_STYLE = { fontSize: 'var(--text-16)', lineHeight: 'var(--leading-16)' } as const;

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(
  { variant, size, loading = false, disabled, className, children, ...rest },
  ref,
) {
  const cls = buttonVariants({ variant, size }) + (className ? ' ' + className : '');
  return (
    <button
      ref={ref}
      className={cls}
      style={LABEL_STYLE}
      disabled={disabled || loading}
      aria-busy={loading || undefined}
      {...rest}
    >
      {loading && (
        <svg
          className="animate-spin"
          style={{ width: 'var(--text-16)', height: 'var(--text-16)' }}
          viewBox="0 0 24 24"
          fill="none"
          aria-hidden="true"
        >
          <circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="3" opacity="0.25" />
          <path d="M21 12a9 9 0 0 0-9-9" stroke="currentColor" strokeWidth="3" strokeLinecap="round" />
        </svg>
      )}
      <span>{children}</span>
    </button>
  );
});
